// <auto-generated />
namespace Point_of_Sale_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class GeneralMovement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GeneralMovement));
        
        string IMigrationMetadata.Id
        {
            get { return "201904270552349_GeneralMovement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
